# Generated by Django 5.2.8 on 2025-11-14 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('quantidade_estoque', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_cliente', models.EmailField(max_length=254)),
                ('status', models.CharField(default='pendente', max_length=20)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.produto')),
            ],
        ),
    ]
