# Generated by Django 5.2.8 on 2025-11-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imgem',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
