# Generated by Django 5.2.8 on 2025-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imgem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
