# Generated by Django 5.2.8 on 2025-11-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_produto_imgem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imgem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
